name: Build DEB Package

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies & Theos
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl git make
          git clone --recursive https://github.com/theos/theos.git /opt/theos
          curl -LO https://github.com/theos/sdks/releases/download/v13.0/iPhoneOS13.0.sdk.tar.xz
          mkdir -p /opt/theos/sdks
          tar -xf iPhoneOS13.0.sdk.tar.xz -C /opt/theos/sdks/
          rm iPhoneOS13.0.sdk.tar.xz

      - name: Build Package
        run: |
          export THEOS=/opt/theos
          make -f Makefile package FINALPACKAGE=1

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stashing-deb
          path: packages/*.deb
